name: ecommerce_model
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  geolocator: ^8.0.1
  brasil_fields: ^1.3.0
  flutter_credit_card: ^3.0.1
  mask_text_input_formatter: ^2.0.0
  flip_card: ^0.6.0
  credit_card_type_detector: ^2.0.0
  keyboard_actions: ^3.4.5
  flutter_staggered_grid_view: ^0.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

get_cli:
  sub_folder: false

flutter:
  uses-material-design: true
